version: '3.7'
services:
  app:
    container_name: go-container
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
    volumes:
    - .:/app
    ports:
    - "5000:5000"
    networks:
    - app_network
    # command: python /app/run.py

  db:
    image: mysql
    container_name: mysql-container
    build: 
      context: ./db
      dockerfile: dockerfile
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    ports:
    - "3306:3306"
    networks:
    - app_network
  
networks:
    app_network:
      driver: bridge